/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author valdir
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


public class RioGUI extends javax.swing.JFrame {

    /**
     * Creates new form RioGUI
     */
    public RioGUI() {
        
        initComponents();
        ressonance2Label.setVisible(false);
        ressonance3Label.setVisible(false);
        ressonance4Label.setVisible(false);
        ressonance5Label.setVisible(false);
        ressonance6Label.setVisible(false);
        ressonance7Label.setVisible(false);
        ressonance8Label.setVisible(false);
        ressonance9Label.setVisible(false);
        ressonance10Label.setVisible(false);
        ressonance11Label.setVisible(false);
        ressonance12Label.setVisible(false);
        
        ressonance2ComboBox.setVisible(false);
        ressonance3ComboBox.setVisible(false);
        ressonance4ComboBox.setVisible(false);
        ressonance5ComboBox.setVisible(false);
        ressonance6ComboBox.setVisible(false);
        ressonance7ComboBox.setVisible(false);
        ressonance8ComboBox.setVisible(false);
        ressonance9ComboBox.setVisible(false);
        ressonance10ComboBox.setVisible(false);
        ressonance11ComboBox.setVisible(false);
        ressonance12ComboBox.setVisible(false);    
        
        valRes_2_re_TextField.setVisible(false);
        valRes_2_im_TextField.setVisible(false);
        valRes_3_re_TextField.setVisible(false);
        valRes_3_im_TextField.setVisible(false);
        valRes_4_re_TextField.setVisible(false);
        valRes_4_im_TextField.setVisible(false);
        valRes_5_re_TextField.setVisible(false);
        valRes_5_im_TextField.setVisible(false);
        valRes_6_re_TextField.setVisible(false);
        valRes_6_im_TextField.setVisible(false);
        valRes_7_re_TextField.setVisible(false);
        valRes_7_im_TextField.setVisible(false);
        valRes_8_re_TextField.setVisible(false);
        valRes_8_im_TextField.setVisible(false);
        valRes_9_re_TextField.setVisible(false);
        valRes_9_im_TextField.setVisible(false);
        valRes_10_re_TextField.setVisible(false);
        valRes_10_im_TextField.setVisible(false);
        valRes_11_re_TextField.setVisible(false);
        valRes_11_im_TextField.setVisible(false);
        valRes_12_re_TextField.setVisible(false);
        valRes_12_im_TextField.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        runRioButton = new javax.swing.JButton();
        setFigurePathLabel = new javax.swing.JLabel();
        rioPathTextField = new javax.swing.JTextField();
        outputFileNameTextView = new javax.swing.JTextField();
        numberOfSamplesTextField = new javax.swing.JTextField();
        finalStateComboBox = new javax.swing.JComboBox<>();
        finalSateLabel = new javax.swing.JLabel();
        numberOfEventsTextField = new javax.swing.JTextField();
        numberOfEventsLabel = new javax.swing.JLabel();
        numberOfSamplesLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seedTypeLabel = new javax.swing.JLabel();
        isGaussianLabel = new javax.swing.JLabel();
        deltaOrGaussianComboBox = new javax.swing.JComboBox<>();
        imaginaryOrRealLabel = new javax.swing.JLabel();
        imaginaryOrRealComboBox = new javax.swing.JComboBox<>();
        ressonancesLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        numberOrRessonancesSpinner = new javax.swing.JSpinner();
        ressonance1Label = new javax.swing.JLabel();
        ressonance1ComboBox = new javax.swing.JComboBox<>();
        ressonance2Label = new javax.swing.JLabel();
        ressonance2ComboBox = new javax.swing.JComboBox<>();
        ressonance3Label = new javax.swing.JLabel();
        ressonance3ComboBox = new javax.swing.JComboBox<>();
        ressonance4Label = new javax.swing.JLabel();
        ressonance5Label = new javax.swing.JLabel();
        ressonance6Label = new javax.swing.JLabel();
        ressonance7Label = new javax.swing.JLabel();
        ressonance8Label = new javax.swing.JLabel();
        ressonance9Label = new javax.swing.JLabel();
        ressonance10Label = new javax.swing.JLabel();
        ressonance11Label = new javax.swing.JLabel();
        ressonance4ComboBox = new javax.swing.JComboBox<>();
        ressonance5ComboBox = new javax.swing.JComboBox<>();
        ressonance6ComboBox = new javax.swing.JComboBox<>();
        ressonance7ComboBox = new javax.swing.JComboBox<>();
        ressonance8ComboBox = new javax.swing.JComboBox<>();
        ressonance9ComboBox = new javax.swing.JComboBox<>();
        ressonance10ComboBox = new javax.swing.JComboBox<>();
        ressonance11ComboBox = new javax.swing.JComboBox<>();
        ressonance12Label = new javax.swing.JLabel();
        ressonance12ComboBox = new javax.swing.JComboBox<>();
        valRes_1_re_TextField = new javax.swing.JTextField();
        valRes_1_im_TextField = new javax.swing.JTextField();
        realLabel = new javax.swing.JLabel();
        imaginaryLabel = new javax.swing.JLabel();
        valRes_2_re_TextField = new javax.swing.JTextField();
        valRes_2_im_TextField = new javax.swing.JTextField();
        valRes_3_re_TextField = new javax.swing.JTextField();
        valRes_3_im_TextField = new javax.swing.JTextField();
        valRes_4_re_TextField = new javax.swing.JTextField();
        valRes_4_im_TextField = new javax.swing.JTextField();
        valRes_5_re_TextField = new javax.swing.JTextField();
        valRes_5_im_TextField = new javax.swing.JTextField();
        valRes_6_re_TextField = new javax.swing.JTextField();
        valRes_6_im_TextField = new javax.swing.JTextField();
        valRes_7_re_TextField = new javax.swing.JTextField();
        valRes_7_im_TextField = new javax.swing.JTextField();
        valRes_8_re_TextField = new javax.swing.JTextField();
        valRes_8_im_TextField = new javax.swing.JTextField();
        valRes_9_re_TextField = new javax.swing.JTextField();
        valRes_9_im_TextField = new javax.swing.JTextField();
        valRes_10_re_TextField = new javax.swing.JTextField();
        valRes_10_im_TextField = new javax.swing.JTextField();
        valRes_11_re_TextField = new javax.swing.JTextField();
        valRes_11_im_TextField = new javax.swing.JTextField();
        valRes_12_re_TextField = new javax.swing.JTextField();
        valRes_12_im_TextField = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rio + GUI");

        runRioButton.setText("run Rio+");
        runRioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runRioButtonActionPerformed(evt);
            }
        });

        setFigurePathLabel.setText("Set here the path of the root dir of Rio+");
        setFigurePathLabel.setToolTipText("Type here the path of Rio+ root directory. This directory should have the content: fit, fractions, GenFit, src and toy.");

        outputFileNameTextView.setText("testNtuple");
        outputFileNameTextView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputFileNameTextViewActionPerformed(evt);
            }
        });

        numberOfSamplesTextField.setText("1");

        finalStateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kkk", "kkpi", "kpipi", "pipipi" }));
        finalStateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalStateComboBoxActionPerformed(evt);
            }
        });

        finalSateLabel.setText("Insert the final state here");

        numberOfEventsTextField.setText("10000");

        numberOfEventsLabel.setText("Number of events to be generated");

        numberOfSamplesLabel.setText("Number of samples");

        jLabel2.setText("Output file name (without .root extension) ");

        seedTypeLabel.setText("Using random seed!");

        isGaussianLabel.setText("Mass distribution delta or a gaussian?");

        deltaOrGaussianComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "delta", "gaussian" }));

        imaginaryOrRealLabel.setText("Real and imaginary parts or as magnitude and phase? ");

        imaginaryOrRealComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "magnitude", "real and imaginary" }));

        ressonancesLabel.setText("Number of Ressonances");

        numberOrRessonancesSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        numberOrRessonancesSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numberOrRessonancesSpinnerStateChanged(evt);
            }
        });

        ressonance1Label.setText("Ressonance 1 -");

        ressonance1ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance2Label.setText("Ressonance 2 -");

        ressonance2ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance3Label.setText("Ressonance 3 -");

        ressonance3ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance4Label.setText("Ressonance 4 -");

        ressonance5Label.setText("Ressonance 5 -");

        ressonance6Label.setText("Ressonance 6 -");

        ressonance7Label.setText("Ressonance 7 -");

        ressonance8Label.setText("Ressonance 8 -");

        ressonance9Label.setText("Ressonance 9 -");

        ressonance10Label.setText("Ressonance 10 -");

        ressonance11Label.setText("Ressonance 11 -");

        ressonance4ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance5ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance6ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance7ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance8ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance9ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance10ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance11ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        ressonance12Label.setText("Ressonance 12 -");

        ressonance12ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "f0(980) pi", "f0(X) pi", "f0(1500) pi", "f0(1710) pi", "3pi NR", "pipi_SW NR", "rho(770) pi", "omega  pi", "rho(1450)  pi", "f2(1270) pi", "f’2(1525) pi", "BE correlation" }));

        valRes_1_re_TextField.setText("0.2");

        valRes_1_im_TextField.setText("0.4");

        realLabel.setText("Real");

        imaginaryLabel.setText("Imaginary");

        valRes_2_re_TextField.setText("0");

        valRes_2_im_TextField.setText("0");

        valRes_3_re_TextField.setText("0");

        valRes_3_im_TextField.setText("0");

        valRes_4_re_TextField.setText("0");

        valRes_4_im_TextField.setText("0");

        valRes_5_re_TextField.setText("0");

        valRes_5_im_TextField.setText("0");

        valRes_6_re_TextField.setText("0");
        valRes_6_re_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valRes_6_re_TextFieldActionPerformed(evt);
            }
        });

        valRes_6_im_TextField.setText("0");

        valRes_7_re_TextField.setText("0");

        valRes_7_im_TextField.setText("0");
        valRes_7_im_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valRes_7_im_TextFieldActionPerformed(evt);
            }
        });

        valRes_8_re_TextField.setText("0");

        valRes_8_im_TextField.setText("0");

        valRes_9_re_TextField.setText("0");

        valRes_9_im_TextField.setText("0");

        valRes_10_re_TextField.setText("0");

        valRes_10_im_TextField.setText("0");

        valRes_11_re_TextField.setText("0");

        valRes_11_im_TextField.setText("0");

        valRes_12_re_TextField.setText("0");

        valRes_12_im_TextField.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(346, 346, 346))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberOfSamplesLabel)
                            .addComponent(jLabel2)
                            .addComponent(finalSateLabel)
                            .addComponent(numberOfEventsLabel)
                            .addComponent(seedTypeLabel)
                            .addComponent(isGaussianLabel)
                            .addComponent(imaginaryOrRealLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ressonance1Label)
                                    .addComponent(ressonancesLabel)
                                    .addComponent(ressonance2Label)
                                    .addComponent(ressonance3Label)
                                    .addComponent(ressonance4Label)
                                    .addComponent(ressonance5Label)
                                    .addComponent(ressonance6Label)
                                    .addComponent(ressonance7Label)
                                    .addComponent(ressonance8Label)
                                    .addComponent(ressonance9Label)
                                    .addComponent(ressonance10Label)
                                    .addComponent(ressonance11Label)
                                    .addComponent(ressonance12Label))
                                .addGap(18, 18, 18)
                                .addComponent(numberOrRessonancesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ressonance1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance11ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance7ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance8ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfEventsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deltaOrGaussianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(finalStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfSamplesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(outputFileNameTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance5ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance6ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance9ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance10ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ressonance12ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valRes_1_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(realLabel)
                                            .addComponent(valRes_2_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_3_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valRes_3_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(imaginaryLabel)
                                            .addComponent(valRes_1_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_2_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(valRes_6_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(valRes_6_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(valRes_5_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(valRes_5_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(valRes_4_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(41, 41, 41)
                                            .addComponent(valRes_4_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valRes_7_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_8_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_9_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_10_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_11_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_12_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(valRes_12_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_11_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_10_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_9_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_8_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(valRes_7_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imaginaryOrRealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(runRioButton)
                                .addGap(51, 51, 51))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(rioPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(261, 261, 261)
                        .addComponent(setFigurePathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {valRes_10_im_TextField, valRes_10_re_TextField, valRes_11_im_TextField, valRes_11_re_TextField, valRes_12_im_TextField, valRes_12_re_TextField, valRes_1_im_TextField, valRes_1_re_TextField, valRes_2_im_TextField, valRes_2_re_TextField, valRes_3_im_TextField, valRes_3_re_TextField, valRes_4_im_TextField, valRes_4_re_TextField, valRes_5_im_TextField, valRes_5_re_TextField, valRes_6_im_TextField, valRes_6_re_TextField, valRes_7_im_TextField, valRes_7_re_TextField, valRes_8_im_TextField, valRes_8_re_TextField, valRes_9_im_TextField, valRes_9_re_TextField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(setFigurePathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rioPathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(outputFileNameTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfSamplesLabel)
                    .addComponent(numberOfSamplesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finalSateLabel)
                    .addComponent(finalStateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfEventsLabel)
                    .addComponent(numberOfEventsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seedTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isGaussianLabel)
                    .addComponent(deltaOrGaussianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imaginaryOrRealLabel)
                    .addComponent(imaginaryOrRealComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runRioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonancesLabel)
                    .addComponent(numberOrRessonancesSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realLabel)
                    .addComponent(imaginaryLabel))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance1Label)
                    .addComponent(ressonance1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_1_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_1_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance2Label)
                    .addComponent(ressonance2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_2_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_2_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance3Label)
                    .addComponent(ressonance3ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_3_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_3_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance4Label)
                    .addComponent(ressonance4ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_4_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_4_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance5Label)
                    .addComponent(ressonance5ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_5_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_5_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance6Label)
                    .addComponent(ressonance6ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_6_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_6_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance7Label)
                    .addComponent(ressonance7ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_7_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_7_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance8Label)
                    .addComponent(ressonance8ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_8_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_8_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance9Label)
                    .addComponent(ressonance9ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_9_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_9_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance10Label)
                    .addComponent(ressonance10ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_10_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_10_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance11Label)
                    .addComponent(ressonance11ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_11_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_11_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ressonance12Label)
                    .addComponent(ressonance12ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_12_re_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valRes_12_im_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ressonance10Label, ressonance11Label, ressonance1Label, ressonance2Label, ressonance3Label, ressonance4Label, ressonance5Label, ressonance6Label, ressonance7Label, ressonance8Label, ressonance9Label});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runRioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runRioButtonActionPerformed
        // TODO add your handling code here:
        
        new RioGUI().executeRio(
                (String) outputFileNameTextView.getText(),
                (String) numberOfSamplesTextField.getText(),
                (String) numberOfEventsTextField.getText(),
                (String) finalStateComboBox.getSelectedItem(), 
                (String) deltaOrGaussianComboBox.getSelectedItem(),
                (String) imaginaryOrRealComboBox.getSelectedItem(),
                //Starting Ressonances,
                (String) ressonance1ComboBox.getSelectedItem(),  (boolean) ressonance1ComboBox.isVisible(),  (String) valRes_1_re_TextField.getText(),  (String) valRes_1_im_TextField.getText(),
                (String) ressonance2ComboBox.getSelectedItem(),  (boolean) ressonance2ComboBox.isVisible(),  (String) valRes_2_re_TextField.getText(),  (String) valRes_2_im_TextField.getText(),
                (String) ressonance3ComboBox.getSelectedItem(),  (boolean) ressonance3ComboBox.isVisible(),  (String) valRes_3_re_TextField.getText(),  (String) valRes_3_im_TextField.getText(),
                (String) ressonance4ComboBox.getSelectedItem(),  (boolean) ressonance4ComboBox.isVisible(),  (String) valRes_4_re_TextField.getText(),  (String) valRes_4_im_TextField.getText(),
                (String) ressonance5ComboBox.getSelectedItem(),  (boolean) ressonance5ComboBox.isVisible(),  (String) valRes_5_re_TextField.getText(),  (String) valRes_5_im_TextField.getText(),
                (String) ressonance6ComboBox.getSelectedItem(),  (boolean) ressonance6ComboBox.isVisible(),  (String) valRes_6_re_TextField.getText(),  (String) valRes_6_im_TextField.getText(),
                (String) ressonance7ComboBox.getSelectedItem(),  (boolean) ressonance7ComboBox.isVisible(),  (String) valRes_7_re_TextField.getText(),  (String) valRes_7_im_TextField.getText(),
                (String) ressonance8ComboBox.getSelectedItem(),  (boolean) ressonance8ComboBox.isVisible(),  (String) valRes_8_re_TextField.getText(),  (String) valRes_8_im_TextField.getText(),
                (String) ressonance9ComboBox.getSelectedItem(),  (boolean) ressonance9ComboBox.isVisible(),  (String) valRes_9_re_TextField.getText(),  (String) valRes_9_im_TextField.getText(),
                (String) ressonance10ComboBox.getSelectedItem(), (boolean) ressonance10ComboBox.isVisible(), (String) valRes_10_re_TextField.getText(), (String) valRes_10_im_TextField.getText(),
                (String) ressonance11ComboBox.getSelectedItem(), (boolean) ressonance11ComboBox.isVisible(), (String) valRes_11_re_TextField.getText(), (String) valRes_11_im_TextField.getText(),
                (String) ressonance12ComboBox.getSelectedItem(), (boolean) ressonance12ComboBox.isVisible(), (String) valRes_12_re_TextField.getText(), (String) valRes_12_im_TextField.getText()
        );        
    }//GEN-LAST:event_runRioButtonActionPerformed

    private void outputFileNameTextViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputFileNameTextViewActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_outputFileNameTextViewActionPerformed

    private void finalStateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalStateComboBoxActionPerformed
        // TODO add your handling code here:
        JComboBox cb = (JComboBox) evt.getSource();
        String selectedItem = (String) cb.getSelectedItem();
        
        
 
    }//GEN-LAST:event_finalStateComboBoxActionPerformed

    private void numberOrRessonancesSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numberOrRessonancesSpinnerStateChanged
        // TODO add your handling code here:
        System.out.println("Spinner value is : " + numberOrRessonancesSpinner.getValue());
        int resNumber = (int)numberOrRessonancesSpinner.getValue();
        if(resNumber == 2){
            ressonance2Label.setVisible(true);
            ressonance2ComboBox.setVisible(true);
            valRes_2_re_TextField.setVisible(true);
            valRes_2_im_TextField.setVisible(true);
        }else if (resNumber < 2) {
            ressonance2Label.setVisible(false);
            ressonance2ComboBox.setVisible(false);
            valRes_2_re_TextField.setVisible(false);
            valRes_2_im_TextField.setVisible(false);
        }
        if(resNumber == 3){
            ressonance3Label.setVisible(true);
            ressonance3ComboBox.setVisible(true);
            valRes_3_re_TextField.setVisible(true);
            valRes_3_im_TextField.setVisible(true);
        }else if (resNumber < 3) {
            ressonance3Label.setVisible(false);
            ressonance3ComboBox.setVisible(false);
            valRes_3_re_TextField.setVisible(false);
            valRes_3_im_TextField.setVisible(false);
        }
        if(resNumber == 4){
            ressonance4Label.setVisible(true);
            ressonance4ComboBox.setVisible(true);
            valRes_4_re_TextField.setVisible(true);
            valRes_4_im_TextField.setVisible(true);
        }else if (resNumber < 4) {
            ressonance4Label.setVisible(false);
            ressonance4ComboBox.setVisible(false);
            valRes_4_re_TextField.setVisible(false);
            valRes_4_im_TextField.setVisible(false);
        }
        if(resNumber == 5){
            ressonance5Label.setVisible(true);
            ressonance5ComboBox.setVisible(true);
            valRes_5_re_TextField.setVisible(true);
            valRes_5_im_TextField.setVisible(true);
        }else if (resNumber < 5) {
            ressonance5Label.setVisible(false);
            ressonance5ComboBox.setVisible(false);
            valRes_5_re_TextField.setVisible(false);
            valRes_5_im_TextField.setVisible(false);
        }
        if(resNumber == 6){
            ressonance6Label.setVisible(true);
            ressonance6ComboBox.setVisible(true);
            valRes_6_re_TextField.setVisible(true);
            valRes_6_im_TextField.setVisible(true);
        }else if (resNumber < 6) {
            ressonance6Label.setVisible(false);
            ressonance6ComboBox.setVisible(false);
            valRes_6_re_TextField.setVisible(false);
            valRes_6_im_TextField.setVisible(false);
        }
        if(resNumber == 7){
            ressonance7Label.setVisible(true);
            ressonance7ComboBox.setVisible(true);
            valRes_7_re_TextField.setVisible(true);
            valRes_7_im_TextField.setVisible(true);
        }else if (resNumber < 7) {
            ressonance7Label.setVisible(false);
            ressonance7ComboBox.setVisible(false);
            valRes_7_re_TextField.setVisible(false);
            valRes_7_im_TextField.setVisible(false);
        }
        if(resNumber == 8){
            ressonance8Label.setVisible(true);
            ressonance8ComboBox.setVisible(true);
            valRes_8_re_TextField.setVisible(true);
            valRes_8_im_TextField.setVisible(true);
        }else if (resNumber < 8) {
            ressonance8Label.setVisible(false);
            ressonance8ComboBox.setVisible(false);
            valRes_8_re_TextField.setVisible(false);
            valRes_8_im_TextField.setVisible(false);
        }
        if(resNumber == 9){
            ressonance9Label.setVisible(true);
            ressonance9ComboBox.setVisible(true);
            valRes_9_re_TextField.setVisible(true);
            valRes_9_im_TextField.setVisible(true);
        }else if (resNumber < 9) {
            ressonance9Label.setVisible(false);
            ressonance9ComboBox.setVisible(false);
            valRes_9_re_TextField.setVisible(false);
            valRes_9_im_TextField.setVisible(false);
        }
        if(resNumber == 10){
            ressonance10Label.setVisible(true);
            ressonance10ComboBox.setVisible(true);
            valRes_10_re_TextField.setVisible(true);
            valRes_10_im_TextField.setVisible(true);
        }else if (resNumber < 10) {
            ressonance10Label.setVisible(false);
            ressonance10ComboBox.setVisible(false);
            valRes_10_re_TextField.setVisible(false);
            valRes_10_im_TextField.setVisible(false);
        }
        if(resNumber == 11){
            ressonance11Label.setVisible(true);
            ressonance11ComboBox.setVisible(true);
            valRes_11_re_TextField.setVisible(true);
            valRes_11_im_TextField.setVisible(true);
        }else if (resNumber < 11) {
            ressonance11Label.setVisible(false);
            ressonance11ComboBox.setVisible(false);
            valRes_11_re_TextField.setVisible(false);
            valRes_11_im_TextField.setVisible(false);
        }
        if(resNumber == 12){
            ressonance12Label.setVisible(true);
            ressonance12ComboBox.setVisible(true);
            valRes_12_re_TextField.setVisible(true);
            valRes_12_im_TextField.setVisible(true);
            
        }else if (resNumber < 12) {
            ressonance12Label.setVisible(false);
            ressonance12ComboBox.setVisible(false);
            valRes_12_re_TextField.setVisible(false);
            valRes_12_im_TextField.setVisible(false);
        }
    }//GEN-LAST:event_numberOrRessonancesSpinnerStateChanged

    private void valRes_6_re_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valRes_6_re_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valRes_6_re_TextFieldActionPerformed

    private void valRes_7_im_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valRes_7_im_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valRes_7_im_TextFieldActionPerformed

    
    private void writeRioInput(
            String outputFileName,
            String numberOfSamples, 
            String numberOfEvents,
            String finalStateSelected, 
            String massDistribution, 
            String realAndImaginary,
            //From now start the ressonances,
            String res1Name,  boolean isRes1,  String valRes1_re,  String valRes1_im, 
            String res2Name,  boolean isRes2,  String valRes2_re,  String valRes2_im, 
            String res3Name,  boolean isRes3,  String valRes3_re,  String valRes3_im, 
            String res4Name,  boolean isRes4,  String valRes4_re,  String valRes4_im,
            String res5Name,  boolean isRes5,  String valRes5_re,  String valRes5_im,
            String res6Name,  boolean isRes6,  String valRes6_re,  String valRes6_im,
            String res7Name,  boolean isRes7,  String valRes7_re,  String valRes7_im,
            String res8Name,  boolean isRes8,  String valRes8_re,  String valRes8_im,
            String res9Name,  boolean isRes9,  String valRes9_re,  String valRes9_im,
            String res10Name, boolean isRes10, String valRes10_re, String valRes10_im,
            String res11Name, boolean isRes11, String valRes11_re, String valRes11_im,
            String res12Name, boolean isRes12, String valRes12_re, String valRes12_im
    )  throws IOException {
        String str = "";
        
        String fileName = "/Users/valdirsalustino/Desktop/tmp/InputFileFromRioGUI.txt"; 
        try (//        BufferedWriter writer = new BufferedWriter(new FileWriter(fileName));
                BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
                str += "#Insert the input file name (without .root) \n \n";
                str += "output_file_name                    aroot_files/"+ outputFileName + "\n\n";
                str += "#Insert the number of samples \n \n ";
                str += "number_of_samples                               " + numberOfSamples + "\n\n";
                str += "#Insert the final state here. (0 = kkpi, 1 = kpipi, 2 = pipipi, 3 = KKK).\n\n";
                if (finalStateSelected == "kkk"){ 
                str += "final_state                                     " + 3 + "\n\n"; 
                }
                else if(finalStateSelected == "pipipi"){
                str += "final_state                                     " + 2 + "\n\n"; 
                }
                else if(finalStateSelected == "kpipi") {
                str += "final_state                                     " + 1 + "\n\n"; 
                }
                else if(finalStateSelected == "kkpi") {
                str += "final_state                                     " + 0 + "\n\n"; 
                }
                
                str +="#Insert the number of events to be generated.\n\n";
                str +="number_of_events                                 " + numberOfEvents + "\n\n";
                str +="#What seed should be used in the generator? (insert 0 for random seed) \n\n";
                str +="seed                                             " + 0 +  "\n\n";
                str +="#Would you like the mass distribution to be a delta or a gaussian? (1 for gaussian and 0 for delta)\n\n";
                if (massDistribution == "delta"){ 
                str += "is_gaussian                                     " + 0 + "\n\n"; 
                }
                else if(massDistribution == "gaussian") {
                str += "is_gaussian                                     " + 1 + "\n\n";
                }
               
                str +="#Background mass distribution represented by a linear equation. Insert Parameters. "
                        + "WARNING: these parameters will be ignored in case delta mass distribution was chosen.\n\n";
                str +="Bkg_par1                                     3000 # Background mass distribution parameter 1\n";
                str +="Bkg_par2                                     2000 # Background mass distribution parameter 2\n\n";
                
                str +="#Would you like the resonant coefficients to be given as real and imaginary parts or as magnitude and phase? (1 for real and imaginary pats, 0 for magnitude and phase)\n\n";
                if (realAndImaginary == "real and imaginary"){
                    str += "real_and_imaginary                      " + 1 + "\n\n";
                }
                else if (realAndImaginary == "magnitude"){
                    str += "real_and_imaginary                      " + 0 + "\n\n";
                }
                
                str+="#Insert the resonant channels real and imaginary parts and set them as fix parameter or not. "
                        + "Comment, erase or insert both real and imaginary parts fixed at 0 for the undesired "
                        + "resonant channels.\n\n";
                
                
                if(isRes1) {
                    str+="############################################################################################################\n";
                    str+="#### " + res1Name + "\n";
                    res1Name = res1Name.replace("(","");
                    res1Name = res1Name.replace(")","+");
                    res1Name = res1Name.replace(" ","");
                    //name += "_re";
                    str+= res1Name+"_re"+"                     " + valRes1_re + "         #real part  \n";
                    str+= res1Name+"_im"+"                     " + valRes1_im + "         #imaginary part. \n";
                }
                
                if(isRes2) {
                    str+="############################################################################################################\n";
                    str+="#### " + res2Name + "\n";
                    res2Name = res2Name.replace("(","");
                    res2Name = res2Name.replace(")","+");
                    res2Name = res2Name.replace(" ","");
                    //name += "_re";
                    str+= res2Name+"_re"+"                     " + valRes2_re + "         #real part  \n";
                    str+= res2Name+"_im"+"                     " + valRes2_im + "         #imaginary part. \n";
                }
                
                if(isRes3) {
                    str+="############################################################################################################\n";
                    str+="#### " + res3Name + "\n";
                    res3Name = res3Name.replace("(","");
                    res3Name = res3Name.replace(")","+");
                    res3Name = res3Name.replace(" ","");
                    //name += "_re";
                    str+= res3Name+"_re"+"                     " + valRes3_re + "         #real part  \n";
                    str+= res3Name+"_im"+"                     " + valRes3_im + "         #imaginary part. \n";
                }
                if(isRes4) {
                    str+="############################################################################################################\n";
                    str+="#### " + res4Name + "\n";
                    res4Name = res4Name.replace("(","");
                    res4Name = res4Name.replace(")","+");
                    res4Name = res4Name.replace(" ","");
                    //name += "_re";
                    str+= res4Name+"_re"+"                     " + valRes4_re + "         #real part  \n";
                    str+= res4Name+"_im"+"                     " + valRes4_im + "         #imaginary part. \n";
                }
                if(isRes5) {
                    str+="############################################################################################################\n";
                    str+="#### " + res5Name + "\n";
                    res5Name = res5Name.replace("(","");
                    res5Name = res5Name.replace(")","+");
                    res5Name = res5Name.replace(" ","");
                    //name += "_re";
                    str+= res5Name+"_re"+"                     " + valRes5_re + "         #real part  \n";
                    str+= res5Name+"_im"+"                     " + valRes5_im + "         #imaginary part. \n";
                }
                if(isRes6) {
                    str+="############################################################################################################\n";
                    str+="#### " + res6Name + "\n";
                    res6Name = res6Name.replace("(","");
                    res6Name = res6Name.replace(")","+");
                    res6Name = res6Name.replace(" ","");
                    //name += "_re";
                    str+= res6Name+"_re"+"                     " + valRes6_re + "         #real part  \n";
                    str+= res6Name+"_im"+"                     " + valRes6_im + "         #imaginary part. \n";
                }
                if(isRes7) {
                    str+="############################################################################################################\n";
                    str+="#### " + res7Name + "\n";
                    res7Name = res7Name.replace("(","");
                    res7Name = res7Name.replace(")","+");
                    res7Name = res7Name.replace(" ","");
                    //name += "_re";
                    str+= res7Name+"_re"+"                     " + valRes7_re + "         #real part  \n";
                    str+= res7Name+"_im"+"                     " + valRes7_im + "         #imaginary part. \n";
                }
                if(isRes8) {
                    str+="############################################################################################################\n";
                    str+="#### " + res8Name + "\n";
                    res8Name = res8Name.replace("(","");
                    res8Name = res8Name.replace(")","+");
                    res8Name = res8Name.replace(" ","");
                    //name += "_re";
                    str+= res8Name+"_re"+"                     " + valRes8_re + "         #real part  \n";
                    str+= res8Name+"_im"+"                     " + valRes8_im + "         #imaginary part. \n";
                }
                if(isRes9) {
                    str+="############################################################################################################\n";
                    str+="#### " + res9Name + "\n";
                    res9Name = res9Name.replace("(","");
                    res9Name = res9Name.replace(")","+");
                    res9Name = res9Name.replace(" ","");
                    //name += "_re";
                    str+= res9Name+"_re"+"                     " + valRes9_re + "         #real part  \n";
                    str+= res9Name+"_im"+"                     " + valRes9_im + "         #imaginary part. \n";
                }
                if(isRes10) {
                    str+="############################################################################################################\n";
                    str+="#### " + res10Name + "\n";
                    res10Name = res10Name.replace("(","");
                    res10Name = res10Name.replace(")","+");
                    res10Name = res10Name.replace(" ","");
                    //name += "_re";
                    str+= res10Name+"_re"+"                     " + valRes10_re + "         #real part  \n";
                    str+= res10Name+"_im"+"                     " + valRes10_im + "         #imaginary part. \n";
                }
                if(isRes11) {
                    str+="############################################################################################################\n";
                    str+="#### " + res11Name + "\n";
                    res11Name = res11Name.replace("(","");
                    res11Name = res11Name.replace(")","+");
                    res11Name = res11Name.replace(" ","");
                    //name += "_re";
                    str+= res11Name+"_re"+"                     " + valRes11_re + "         #real part  \n";
                    str+= res11Name+"_im"+"                     " + valRes11_im + "         #imaginary part. \n";
                }
                if(isRes12) {
                    str+="############################################################################################################\n";
                    str+="#### " + res12Name + "\n";
                    res12Name = res12Name.replace("(","");
                    res12Name = res12Name.replace(")","+");
                    res12Name = res12Name.replace(" ","");
                    //name += "_re";
                    str+= res12Name+"_re"+"                     " + valRes12_re + "         #real part  \n";
                    str+= res12Name+"_im"+"                     " + valRes12_im + "         #imaginary part. \n";
                }
                
                
                writer.write(str);
        }
    }
    
    private void executeRio(
            String outputFileName,
            String numberOfSamples,
            String numberOfEvents,
            String finalStateSelected, 
            String massDistribution,
            String realAndImaginary,
            //starting ressonances,
            String res1Name,  boolean isRes1,  String valRes1_re,  String valRes1_im, 
            String res2Name,  boolean isRes2,  String valRes2_re,  String valRes2_im, 
            String res3Name,  boolean isRes3,  String valRes3_re,  String valRes3_im, 
            String res4Name,  boolean isRes4,  String valRes4_re,  String valRes4_im, 
            String res5Name,  boolean isRes5,  String valRes5_re,  String valRes5_im, 
            String res6Name,  boolean isRes6,  String valRes6_re,  String valRes6_im, 
            String res7Name,  boolean isRes7,  String valRes7_re,  String valRes7_im, 
            String res8Name,  boolean isRes8,  String valRes8_re,  String valRes8_im, 
            String res9Name,  boolean isRes9,  String valRes9_re,  String valRes9_im, 
            String res10Name, boolean isRes10, String valRes10_re, String valRes10_im, 
            String res11Name, boolean isRes11, String valRes11_re, String valRes11_im, 
            String res12Name, boolean isRes12, String valRes12_re, String valRes12_im 
    ) {
        
        try {
            new RioGUI().writeRioInput(
                    outputFileName,
                    numberOfSamples,
                    numberOfEvents,
                    finalStateSelected,
                    massDistribution,
                    realAndImaginary,
                    //starting ressonances
                     res1Name,  isRes1,  valRes1_re,  valRes1_im, 
                     res2Name,  isRes2,  valRes2_re,  valRes2_im, 
                     res3Name,  isRes3,  valRes3_re,  valRes3_im, 
                     res4Name,  isRes4,  valRes4_re,  valRes4_im, 
                     res5Name,  isRes5,  valRes5_re,  valRes5_im, 
                     res6Name,  isRes6,  valRes6_re,  valRes6_im, 
                     res7Name,  isRes7,  valRes7_re,  valRes7_im, 
                     res8Name,  isRes8,  valRes8_re,  valRes8_im, 
                     res9Name,  isRes9,  valRes9_re,  valRes9_im, 
                     res10Name, isRes10, valRes10_re, valRes10_im, 
                     res11Name, isRes11, valRes11_re, valRes11_im, 
                     res12Name, isRes12, valRes12_re, valRes12_im
            );
        } catch (IOException ex) {
            Logger.getLogger(RioGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        StringBuilder buffer = new StringBuilder();
        Process p;
        //String command = "/Users/valdirsalustino/Desktop/tmp/runRio.sh";
        //String command = "open /Users/valdirsalustino/Desktop/tmp/hsum.C";
        //String command = "root -l /home/valdir/Documents/tutorials/hist/hsum.C";
        //String command = "/bin/bash -c root -l /Users/valdirsalustino/Desktop/tmp/hsum.C";
        String command = "/Users/valdirsalustino/Desktop/tmp/runRio.sh";
        try{
            p = Runtime.getRuntime().exec(command);
            p.waitFor();   
            BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()));
        }catch (IOException | InterruptedException e){
        } 
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RioGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new RioGUI().setVisible(true);  
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> deltaOrGaussianComboBox;
    private javax.swing.JLabel finalSateLabel;
    private javax.swing.JComboBox<String> finalStateComboBox;
    private javax.swing.JLabel imaginaryLabel;
    private javax.swing.JComboBox<String> imaginaryOrRealComboBox;
    private javax.swing.JLabel imaginaryOrRealLabel;
    private javax.swing.JLabel isGaussianLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel numberOfEventsLabel;
    private javax.swing.JTextField numberOfEventsTextField;
    private javax.swing.JLabel numberOfSamplesLabel;
    private javax.swing.JTextField numberOfSamplesTextField;
    private javax.swing.JSpinner numberOrRessonancesSpinner;
    private javax.swing.JTextField outputFileNameTextView;
    private javax.swing.JLabel realLabel;
    private javax.swing.JComboBox<String> ressonance10ComboBox;
    private javax.swing.JLabel ressonance10Label;
    private javax.swing.JComboBox<String> ressonance11ComboBox;
    private javax.swing.JLabel ressonance11Label;
    private javax.swing.JComboBox<String> ressonance12ComboBox;
    private javax.swing.JLabel ressonance12Label;
    private javax.swing.JComboBox<String> ressonance1ComboBox;
    private javax.swing.JLabel ressonance1Label;
    private javax.swing.JComboBox<String> ressonance2ComboBox;
    private javax.swing.JLabel ressonance2Label;
    private javax.swing.JComboBox<String> ressonance3ComboBox;
    private javax.swing.JLabel ressonance3Label;
    private javax.swing.JComboBox<String> ressonance4ComboBox;
    private javax.swing.JLabel ressonance4Label;
    private javax.swing.JComboBox<String> ressonance5ComboBox;
    private javax.swing.JLabel ressonance5Label;
    private javax.swing.JComboBox<String> ressonance6ComboBox;
    private javax.swing.JLabel ressonance6Label;
    private javax.swing.JComboBox<String> ressonance7ComboBox;
    private javax.swing.JLabel ressonance7Label;
    private javax.swing.JComboBox<String> ressonance8ComboBox;
    private javax.swing.JLabel ressonance8Label;
    private javax.swing.JComboBox<String> ressonance9ComboBox;
    private javax.swing.JLabel ressonance9Label;
    private javax.swing.JLabel ressonancesLabel;
    private javax.swing.JTextField rioPathTextField;
    private javax.swing.JButton runRioButton;
    private javax.swing.JLabel seedTypeLabel;
    private javax.swing.JLabel setFigurePathLabel;
    private javax.swing.JTextField valRes_10_im_TextField;
    private javax.swing.JTextField valRes_10_re_TextField;
    private javax.swing.JTextField valRes_11_im_TextField;
    private javax.swing.JTextField valRes_11_re_TextField;
    private javax.swing.JTextField valRes_12_im_TextField;
    private javax.swing.JTextField valRes_12_re_TextField;
    private javax.swing.JTextField valRes_1_im_TextField;
    private javax.swing.JTextField valRes_1_re_TextField;
    private javax.swing.JTextField valRes_2_im_TextField;
    private javax.swing.JTextField valRes_2_re_TextField;
    private javax.swing.JTextField valRes_3_im_TextField;
    private javax.swing.JTextField valRes_3_re_TextField;
    private javax.swing.JTextField valRes_4_im_TextField;
    private javax.swing.JTextField valRes_4_re_TextField;
    private javax.swing.JTextField valRes_5_im_TextField;
    private javax.swing.JTextField valRes_5_re_TextField;
    private javax.swing.JTextField valRes_6_im_TextField;
    private javax.swing.JTextField valRes_6_re_TextField;
    private javax.swing.JTextField valRes_7_im_TextField;
    private javax.swing.JTextField valRes_7_re_TextField;
    private javax.swing.JTextField valRes_8_im_TextField;
    private javax.swing.JTextField valRes_8_re_TextField;
    private javax.swing.JTextField valRes_9_im_TextField;
    private javax.swing.JTextField valRes_9_re_TextField;
    // End of variables declaration//GEN-END:variables

}